spring.application.name=finatiol-configuracion-ms
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/alanriverocd/finatiol-configuracion-ms.git
spring.cloud.config.server.git.default-label=main